# OpenVPN Access Server Outputs
output "openvpn_admin_ui" {
  description = "OpenVPN Access Server Admin UI URL"
  value = {
    for k, v in aws_eip.this : k => "https://${v.public_ip}:943/admin"
  }
}

output "openvpn_client_ui" {
  description = "OpenVPN Access Server Client UI URL"  
  value = {
    for k, v in aws_eip.this : k => "https://${v.public_ip}:943/"
  }
}

output "openvpn_public_ips" {
  description = "OpenVPN Server Public IP addresses"
  value = {
    for k, v in aws_eip.this : k => v.public_ip
  }
}

output "openvpn_admin_password_ssm" {
  description = "AWS Systems Manager Parameter Store path for OpenVPN admin password"
  value = aws_ssm_parameter.openvpn_password.name
}

output "ssh_key_name" {
  description = "SSH Key Pair name for EC2 access"
  value = module.key_pair.key_pair_name
}



output "ssh_private_key_openssh" {
  description = "The private key (in OpenSSH format) generated by the key_pair module"
  value = module.key_pair.private_key_openssh
  sensitive = true
}

output "ssh_connection_info" {
  description = "SSH connection information for all instances"
  value = {
    for k, v in var.ec2_complet : k => {
      public_ip    = aws_eip.this[k].public_ip
      public_dns   = aws_eip.this[k].public_dns
      ssh_command  = "ssh -i ${local.name}-${local.region_prefix}-key.pem ec2-user@${aws_eip.this[k].public_ip}"
      key_file     = "${local.name}-${local.region_prefix}-key.pem"
      ssh_script   = "./ssh_to_${k}.sh"
    }
  }
}

output "ready_to_connect" {
  description = "Ready-to-use SSH commands and connection info"
  value = <<-EOT
  
  🔑 SSH Key File: ${local.name}-${local.region_prefix}-key.pem
  
  📋 Connection Commands:
  ${join("\n  ", [for k, v in var.ec2_complet : "• ${k}: ssh -i ${local.name}-${local.region_prefix}-key.pem ec2-user@${aws_eip.this[k].public_ip}"])}
  
  🚀 Quick Connect Scripts:
  ${join("\n  ", [for k, v in var.ec2_complet : "• ./${path.module}/ssh_to_${k}.sh"])}
  
  🌐 OpenVPN Access:
  ${join("\n  ", [for k, v in var.ec2_complet : "• Admin UI: https://${aws_eip.this[k].public_ip}:943/admin"])}
  ${join("\n  ", [for k, v in var.ec2_complet : "• Client UI: https://${aws_eip.this[k].public_ip}:943/"])}
  
  🔐 Get OpenVPN Admin Password:
  aws ssm get-parameter --name "/sagi/openvpn/admin-password" --with-decryption --query 'Parameter.Value' --output text
  
  EOT
}

# Add outputs for instance and test request IDs
output "instance_ids" {
  description = "IDs of the EC2 instances"
  value = {
    for k, v in module.ec2_complete : k => v.id
  }
}


# Add output for EIP associations
output "eip_associations" {
  description = "EIP associations for the instances"
  value = {
    for k, v in aws_eip_association.this : k => {
      instance_id = v.instance_id
      public_ip   = aws_eip.this[k].public_ip
      public_dns  = aws_eip.this[k].public_dns
    }
  }
}